
Start Training: Epoch 1
TRAIN AUC : 0.7140473352028399 ACC : 0.7064358052923881
VALID AUC : 0.7301217128421338 ACC : 0.6616915422885572
Start Training: Epoch 2
TRAIN AUC : 0.7340807591476499 ACC : 0.7244909071109659
VALID AUC : 0.7328292086922666 ACC : 0.6572139303482587
Start Training: Epoch 3
TRAIN AUC : 0.7400711514991427 ACC : 0.7272568877273222
VALID AUC : 0.7339414826402616 ACC : 0.6706467661691542
Start Training: Epoch 4
TRAIN AUC : 0.7402925324051202 ACC : 0.7270390939780028
VALID AUC : 0.7343318240794863 ACC : 0.6512437810945274
Start Training: Epoch 5
TRAIN AUC : 0.7419791637275777 ACC : 0.7274964608515736
VALID AUC : 0.7341784756569336 ACC : 0.6721393034825871
Start Training: Epoch 6
TRAIN AUC : 0.7408248026164891 ACC : 0.7286072089731025
VALID AUC : 0.735044794667458 ACC : 0.6462686567164179
Start Training: Epoch 7
TRAIN AUC : 0.7423020941935333 ACC : 0.7289556789720135
VALID AUC : 0.7349342643109428 ACC : 0.6472636815920398
Start Training: Epoch 8
TRAIN AUC : 0.7418638549025537 ACC : 0.7288685614722857
VALID AUC : 0.7367664792297528 ACC : 0.6288557213930348
Start Training: Epoch 9
TRAIN AUC : 0.7440019756366972 ACC : 0.7278449308504846
VALID AUC : 0.7374047671444034 ACC : 0.6378109452736318
Start Training: Epoch 10
TRAIN AUC : 0.746020656674333 ACC : 0.7301317652183382
VALID AUC : 0.7384114895807713 ACC : 0.6776119402985075
Start Training: Epoch 11
TRAIN AUC : 0.7481009359317994 ACC : 0.7309158227158881
VALID AUC : 0.7455581235331078 ACC : 0.6855721393034826
Start Training: Epoch 12
TRAIN AUC : 0.7486994186124074 ACC : 0.7329413045845584
VALID AUC : 0.7437438324558949 ACC : 0.6497512437810945
Start Training: Epoch 13
Traceback (most recent call last):
  File "/opt/conda/envs/dkt/lib/python3.8/multiprocessing/resource_sharer.py", line 143, in _serve
    msg = conn.recv()
  File "/opt/conda/envs/dkt/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/envs/dkt/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/envs/dkt/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError